local OFFSET = 3

function init(self)
	self.time = 0
	self.pos = go.get_position()
end

--function final(self)
--end

function update(self, dt)
	self.time = self.time + dt * 3

	local curentPos = vmath.vector3(self.pos)
	curentPos.y = self.pos.y + (math.sin(self.time) + 1) * OFFSET

	go.set_position(curentPos)
end

--function on_message(self, message_id, message, sender)
--end

--function on_reload(self)
--end
