function init(self)
	msg.post(".", "acquire_input_focus")

	load_level01()
end

--function final(self)
--end

function load_level01()
	msg.post("#level01", "load")
end

--function update(self, dt)
--end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		print("loaded!")
		msg.post(sender, "init")
		msg.post(sender, "enable")
	end
end

--function on_input(self, action_id, action)
--end
